FROM ubuntu:jammy

LABEL maintainer.name="Luigi Pertoldi"
LABEL maintainer.email="gipert@pm.me"

ARG GEANT4_VERSION="11.2.2"
ARG CMAKE_BUILD_TYPE="Release"

ARG N_THREADS="8"

USER root
WORKDIR /root

# configure system
COPY packages packages.extra .
RUN apt-get update -qq && \
    ln -sf /usr/share/zoneinfo/UTC /etc/localtime && \
    apt-get -y install $(cat packages packages.extra) && \
    locale-gen en_US.UTF-8 && update-locale && \
    rm -rf /var/lib/apt/lists/* && \
# https://askubuntu.com/questions/1034313/ubuntu-18-4-libqt5core-so-5-cannot-open-shared-object-file-no-such-file-or-dir
    strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

ENV LC_ALL="en_US.utf8" \
    LANGUAGE="en_US.utf8" \
    LANG="en_US.utf8"

# build and install GEANT4
RUN mkdir -p src build /opt/geant4 && \
    wget -q -O- "https://cern.ch/geant4-data/releases/geant4-v${GEANT4_VERSION}.tar.gz" \
        | tar --strip-components 1 -C src --strip=1 -x -z && \
    cd build && \
    cmake \
        -DCMAKE_INSTALL_PREFIX="/opt/geant4" \
        -DCMAKE_CXX_STANDARD=17 \
        -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
        -DGEANT4_USE_GDML=ON \
        -DGEANT4_INSTALL_DATA=ON \
        -DGEANT4_INSTALL_DATASETS_TENDL=ON \
        -DGEANT4_USE_SYSTEM_EXPAT=ON \
        -DGEANT4_USE_SYSTEM_ZLIB=ON \
# better to use the officially supported CLHEP version
        -DGEANT4_USE_SYSTEM_CLHEP=OFF \
        -DGEANT4_BUILD_MULTITHREADED=ON \
        ../src && \
    make -j ${N_THREADS} install && \
    cd .. && rm -rf src build

# there's no alternative to setting env vars explicitly
ENV PATH="/opt/geant4/bin:$PATH" \
    LD_LIBRARY_PATH="/opt/geant4/lib:$LD_LIBRARY_PATH"

CMD /bin/bash

# vim: ft=dockerfile
