FROM ubuntu:jammy

LABEL maintainer.name="Luigi Pertoldi"
LABEL maintainer.email="gipert@pm.me"

ARG ROOT_VERSION="6.28.04"
ARG VECGEOM_VERSION="v1.2.6"
ARG GEANT4_VERSION="11.2.2"
ARG BXDECAY0_VERSION="1.1.2"
ARG CMAKE_BUILD_TYPE="Release"

# experimental feature in Geant4, enable at your own risk
ARG GEANT4_USE_USOLIDS="OFF"

USER root
WORKDIR /root

# configure system
COPY packages packages
RUN apt-get update -qq && \
    ln -sf /usr/share/zoneinfo/UTC /etc/localtime && \
    DEBIAN_FRONTEND="noninteractive" apt-get -y install $(cat packages) && \
    locale-gen en_US.UTF-8 && update-locale && \
    rm -rf /var/lib/apt/lists/* && \
# https://askubuntu.com/questions/1034313/ubuntu-18-4-libqt5core-so-5-cannot-open-shared-object-file-no-such-file-or-dir
    strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

ENV LC_ALL="en_US.utf8" \
    LANGUAGE="en_US.utf8" \
    LANG="en_US.utf8"

# build and install VecGeom
RUN mkdir -p src build /opt/vecgeom && \
    wget -q -O- "https://gitlab.cern.ch/VecGeom/VecGeom/-/archive/${VECGEOM_VERSION}/VecGeom-${VECGEOM_VERSION}.tar.gz" \
        | tar --strip-components 1 -C src --strip=1 -x -z && \
    cd build && \
    cmake \
        -DCMAKE_INSTALL_PREFIX="/opt/vecgeom" \
        -DCMAKE_CXX_STANDARD=17 \
        -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
        -DVECGEOM_GDML=ON \
        -DVECGEOM_BUILTIN_VECCORE=ON \
        -Dfail-on-missing=ON \
        ../src && \
    make -j"$(nproc)" install && \
    cd .. && rm -rf build src

ENV PATH="/opt/vecgeom/bin:$PATH" \
    LD_LIBRARY_PATH="/opt/vecgeom/lib:$LD_LIBRARY_PATH"

# build install ROOT
RUN mkdir -p src build /opt/root && \
    wget -q -O- "https://root.cern/download/root_v${ROOT_VERSION}.source.tar.gz" \
        | tar --strip-components 1 -C src --strip=1 -x -z && \
    cd build && \
    cmake \
        -DCMAKE_INSTALL_PREFIX="/opt/root" \
# ROOT is bad software: https://root.cern/install/build_from_source/#caveats
        -DCMAKE_CXX_STANDARD=17 \
        -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
        -Dbuiltin_veccore=OFF \
        -Dgdml=ON \
        -Dminimal=ON \
        -Dfail-on-missing=ON \
        ../src && \
    VERBOSE=1 make -j"$(nproc)" install && \
    cd .. && rm -rf build src

# install ROOT binary release
# RUN mkdir -p /opt/root && \
#     wget -q -O- "https://root.cern/download/root_v${ROOT_VERSION}.Linux-ubuntu20-x86_64-gcc9.3.tar.gz" \
#         | tar --strip-components 1 -xz -C "/opt/root"

ENV ROOTSYS="/opt/root" \
    PATH="/opt/root/bin:$PATH" \
    LD_LIBRARY_PATH="/opt/root/lib:$LD_LIBRARY_PATH" \
    MANPATH="/opt/root/man:$MANPATH" \
    PYTHONPATH="/opt/root/lib:$PYTHONPATH"

# build and install GEANT4
RUN mkdir -p src build /opt/geant4 && \
    wget -q -O- "https://cern.ch/geant4-data/releases/geant4-v${GEANT4_VERSION}.tar.gz" \
        | tar --strip-components 1 -C src --strip=1 -x -z && \
    cd build && \
    cmake \
        -DCMAKE_INSTALL_PREFIX="/opt/geant4" \
        -DCMAKE_CXX_STANDARD=17 \
        -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
        -DGEANT4_USE_GDML=ON \
        -DGEANT4_INSTALL_DATA=ON \
        -DGEANT4_INSTALL_DATASETS_TENDL=ON \
        -DGEANT4_USE_SYSTEM_EXPAT=ON \
        -DGEANT4_USE_SYSTEM_ZLIB=ON \
# better to use the officially supported CLHEP version
        -DGEANT4_USE_SYSTEM_CLHEP=OFF \
        -DGEANT4_BUILD_MULTITHREADED=ON \
# libhdf5must be compiled in thread-safe mode, if GEANT4 multithreading is enabled
        -DGEANT4_USE_HDF5=ON \
        -DGEANT4_USE_USOLIDS=${GEANT4_USE_USOLIDS} \
        -DGEANT4_USE_QT=ON \
        -DGEANT4_USE_INVENTOR_QT=ON \
        -DGEANT4_USE_OPENGL_X11=ON \
        -DGEANT4_USE_RAYTRACER_X11=ON \
        ../src && \
    make -j"$(nproc)" install && \
    cd .. && rm -rf src build

ENV PATH="/opt/geant4/bin:$PATH" \
    LD_LIBRARY_PATH="/opt/geant4/lib:$LD_LIBRARY_PATH"

RUN mkdir -p src build /opt/bxdecay0 && \
    git lfs install && \
    if [ "${BXDECAY0_VERSION}" = "git" ]; then \
        git clone "https://github.com/BxCppDev/bxdecay0" src; \
    else \
        wget -q -O- "https://github.com/BxCppDev/bxdecay0/archive/${BXDECAY0_VERSION}.tar.gz" | tar --strip-components 1 -C src --strip=1 -x -z; \
    fi && \
    cd build && \
    cmake \
        -DCMAKE_INSTALL_PREFIX="/opt/bxdecay0" \
        -DCMAKE_CXX_STANDARD=17 \
        -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
        -DBXDECAY0_WITH_GEANT4_EXTENSION=ON \
        # -DBXDECAY0_INSTALL_DBD_GA_DATA=ON \
        ../src && \
    make -j"$(nproc)" install && \
    rm -rf build src

ENV PATH="/opt/bxdecay0/bin:$PATH" \
    LD_LIBRARY_PATH="/opt/bxdecay0/lib:$LD_LIBRARY_PATH"

COPY python-packages python-packages
RUN pip install uv && \
    uv venv /opt/python-extra && \
    . /opt/python-extra/bin/activate && \
    uv pip install $(cat python-packages)

# this should be enough to load the virtual environment?
ENV PATH="/opt/python-extra/bin:$PATH" \
    VIRTUAL_ENV=/opt/python-extra

CMD /bin/bash

# vim: ft=dockerfile
